# Generated by Django 4.1.7 on 2023-03-26 10:05

import apps.profiles.models
import apps.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default/default_profile_image.png', upload_to=apps.profiles.models.rename_profile_image, verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[apps.profiles.validators.CustomUsernameValidator(), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
